version : '3.8'
services: 
  miniserver:
    image: server: v4
      build: ../5
      container_name: server4

  nginxer:
    image: nginx:latest
    container_name: nginxer
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      